services:
  nginx:
    image: nginx:1.25.3
    container_name: nginx
    env_file:
      - .env
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot 
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - permission-engine
    networks:
      - permission_engine_network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    env_file:
      - .env
    command: certbot certonly --webroot --webroot-path=/var/www/certbot --email $EMAIL_CERTIFICATOR --agree-tos --no-eff-email -d engine.permissioning.city
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $!; certbot renew; done'"
    networks:
      - permission_engine_network
  
  redis:
    image: redis:7.2.5
    container_name: redis
    volumes:
      - ./data/redis:/data
    env_file:
      - .env
    networks:
      - permission_engine_network

  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    networks:
      - permission_engine_network

  permission-engine:
    build:
      context: ./permission-engine
    container_name: permission-engine
    env_file:
      - .env
    volumes:
      - ./logs/permission-engine:/app/log
      - ./permission-engine:/app
      - /app/node_modules
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    command: ["npm", "run", "start:dev"]
    depends_on:
      - postgres
    restart: always
    networks:
      - permission_engine_network

  ptc-dashboard:
    build:
      context: ./ptc-dashboard
    container_name: ptc-dashboard
    env_file:
      - .env
    volumes:
      - ./ptc-dashboard:/app
      - /app/node_modules
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    command: ["npm", "run", "start"]
    depends_on:
      - permission-engine
    restart: always
    networks:
      - permission_engine_network

networks:
  permission_engine_network:
    driver: bridge
