global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'permission_engine_api'
    static_configs:
      - targets: ['permission-engine-api:3000'] # Make sure your NestJS app exposes /metrics
